Add "You-" as a prefix if it's you (:
Hypixel-Translators/hypixel-translators-bot pull request #366
Opened 2021-06-20 21:28 UTC by MaitreRouge

**Please describe the changes this PR makes and why it should be merged**
Soo this pull request is very important, fix a major flaw in the potato farm and I think our production will increse after the merge (maybe +47%)
Nah I'm just kidding, I'm just lonely, I feel bad and I rly want a hug

Ow, beside my mental health being rly bad, this PR add a "YOU -" prefix on the levels page if it's you (:

**In this PR:**
- Code changes were not tested
- Strings were edited (text changed while the key stayed the same)

2021-06-20 21:31 UTC, ImRodry submitted a review, later dismissed
You should add a string just with the text "YOU" and then add it to the right side of the member tag, instead of the left side.
Also you can remove the comment, it will work :)

2021-06-20 21:47 UTC, MaitreRouge commented
I applied ethe changes I was asked for

2021-06-20 21:49 UTC, ImRodry commented on src/commands/Info/levels.ts
> +        } else pageEmbed.addField(getString("unranked", { rank: (i + 1) + (page * 24) }), `<@!${pages[page][i].id}> ${pages[page][i].id === interaction.user.id ? getString("youIndicator") : ""}`, tru
```suggestion
        } else pageEmbed.addField(getString("unranked", { rank: (i + 1) + (page * 24) }), `<@!${pages[page][i].id}> ${pages[page][i].id === interaction.user.id ? ` - ${getString("youIndicator")}` : ""}`, true)
```

2021-06-20 22:25 UTC, MaitreRouge commented
Think I've done everything needed, gtg watch smth on netflix now :D

2021-06-20 22:32 UTC, ImRodry commented
@Mergifyio refresh

2021-06-20 22:41 UTC, ImRodry requested changes
Ignore whatever this is

2021-06-20 22:41 UTC, ImRodry commented on src/commands/Info/levels.ts
>              pageEmbed.addField(getString("level", { rank: (i + 1) + (page * 24), level: pages[page][i].levels!.level, xp: totalXp > 1000 ? `${(totalXp / 1000).toFixed(2)}${getString("thousand")}` : t
Forgot this line ;)
```suggestion
            pageEmbed.addField(getString("level", { rank: (i + 1) + (page * 24), level: pages[page][i].levels!.level, xp: totalXp > 1000 ? `${(totalXp / 1000).toFixed(2)}${getString("thousand")}` : totalXp }), `<@!${pages[page][i].id}>${pages[page][i].id === interaction.user.id ? ` - ${getString("youIndicator")}` : ""}`, true)
```

2021-06-20 22:45 UTC, ImRodry requested changes
Now for real

2021-06-20 22:45 UTC, ImRodry commented on src/commands/Info/levels.ts
>              pageEmbed.addField(getString("level", { rank: (i + 1) + (page * 24), level: pages[page][i].levels!.level, xp: totalXp > 1000 ? `${(totalXp / 1000).toFixed(2)}${getString("thousand")}` : t
Forgot this line
```suggestion
            pageEmbed.addField(getString("level", { rank: (i + 1) + (page * 24), level: pages[page][i].levels!.level, xp: totalXp > 1000 ? `${(totalXp / 1000).toFixed(2)}${getString("thousand")}` : totalXp }), `<@!${pages[page][i].id}>${pages[page][i].id === interaction.user.id ? ` - **${getString("youIndicator")}**` : ""}`, true)
```

2021-06-20 22:45 UTC, ImRodry commented on src/commands/Info/levels.ts
> +        } else pageEmbed.addField(getString("unranked", { rank: (i + 1) + (page * 24) }), `<@!${pages[page][i].id}>${pages[page][i].id === interaction.user.id ? ` - ${getString("youIndicator")}` : ""
Making this bold looks better
```suggestion
        } else pageEmbed.addField(getString("unranked", { rank: (i + 1) + (page * 24) }), `<@!${pages[page][i].id}>${pages[page][i].id === interaction.user.id ? ` - **${getString("youIndicator")}**` : ""}`, true)
```

2021-06-21 09:49 UTC, ImRodry approved these changes
Looks good, thank you for your help!

2021-06-21 09:49 UTC, merged