Use `message.reply` instance of pinging the user
Hypixel-Translators/hypixel-translators-bot pull request #421
Opened 2021-08-05 15:36 UTC by Syjalo

**Please describe the changes this PR makes and why it should be merged**
To make the message look more beautiful.

**In this PR:**

- Code changes were not tested

2021-08-05 15:43 UTC, ImRodry requested changes
Please remove this and remove `repliedUser: false` from index as that's not doing anything atm

2021-08-05 15:43 UTC, ImRodry commented on src/listeners/messageCreate.ts
> +                await message.reply({ embeds: [embed], allowedMentions: { repliedUser: true } })
```suggestion
                await message.reply({ embeds: [embed] })
```

2021-08-05 15:43 UTC, ImRodry commented on src/listeners/messageCreate.ts
> +                await message.reply({ embeds: [embed], allowedMentions: { repliedUser: true } })
```suggestion
                await message.reply({ embeds: [embed] })
```

2021-08-06 07:58 UTC, Syjalo commented
> Please remove this and remove `repliedUser: false` from index as that's not doing anything atm

Btw, you have access to my Syjalo:patch-5 repository.

2021-08-06 10:31 UTC, ImRodry commented
I know I do but I wanted you to do it. 
Also GitHub lets you add suggestions to a batch so you can commit them all at once in the files tab

2021-08-06 10:32 UTC, merged