feat: nickname prefix vadalidation
Hypixel-Translators/hypixel-translators-bot pull request #648
Opened 2022-02-23 21:47 UTC by marzeq

**Please describe the changes this PR makes and why it should be merged**
Adds a system that checks if a persons prefix is a flag (or a language code in case of Chinese) when a user updates their nickname.

**In this PR:**
- Code changes have been tested against on a separate test bot

2022-02-24 09:32 UTC, Syjalo requested changes
Author and field now is objects

2022-02-24 09:32 UTC, Syjalo commented on src/listeners/guildMemberUpdate.ts
> +				author: "Received a message from staff",
```suggestion
				author: { name: "Received a message from staff" },
```

2022-02-24 09:32 UTC, Syjalo commented on src/listeners/guildMemberUpdate.ts
> +				author: "Received a message from staff",
```suggestion
				author: { name: "Received a message from staff" },
```

2022-04-03 02:00 UTC, ImRodry approved these changes

2022-04-03 02:01 UTC, merged